"""
Django settings for proyectosimuladorFisica project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v@b^u*w9kg%9&u8b_ggptzyf(&q@hj6wc1qqnh=8*yfh*z!56e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app','localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  
    'whitenoise.runserver_nostatic',
    'django.contrib.auth',          
    'django.contrib.contenttypes',  
    'django.contrib.sessions',      
    'django.contrib.messages',      
    'django.contrib.staticfiles',   
    'django.contrib.humanize',     
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyectosimuladorFisica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyectosimuladorFisica.wsgi.app'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Simuladordefisica',  
        'USER': 'postgres',         
        'PASSWORD': 'miclave123',
        'HOST': 'localhost',        
        'PORT': '5432',              
    }
}


# Configuración para archivos grandes
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500MB en bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500MB en bytes
MAX_UPLOAD_SIZE = 524288000  # 500MB en bytes

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# ✅ CONFIGURACIÓN PARA BOLIVIA
LANGUAGE_CODE = 'es-es'  # Español
TIME_ZONE = 'America/La_Paz'  # Zona horaria de Bolivia
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CONFIGURACIÓN ADICIONAL PARA REPORTES PDF 

# Directorio para almacenar reportes PDF temporales
REPORTS_DIR = os.path.join(BASE_DIR, 'reportes_pdf')
if not os.path.exists(REPORTS_DIR):
    os.makedirs(REPORTS_DIR)

# Configuración para generación de PDFs
PDF_SETTINGS = {
    'PAGE_SIZE': 'A4',
    'MARGINS': (40, 40, 40, 40),  # izquierda, arriba, derecha, abajo
    'TITLE': 'Sistema de Laboratorios de Física VR',
    'AUTHOR': 'Administrador del Sistema',
}

# Configuración de sesión para el dashboard
SESSION_COOKIE_AGE = 3600  # 1 hora de sesión
SESSION_SAVE_EVERY_REQUEST = True

# Configuración para login
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/home-cliente/'
LOGOUT_REDIRECT_URL = '/login/'