# Generated by Django 5.2.5 on 2025-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(blank=True, max_length=128, null=True)),
                ('tipo', models.CharField(choices=[('estudiante', 'Estudiante'), ('universitario', 'Universitario'), ('profesional', 'Profesional')], default='estudiante', max_length=20)),
                ('foto', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
