# Generated by Django 5.2.7 on 2025-10-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('archivo_pdf', models.BinaryField(blank=True, null=True, verbose_name='Archivo PDF')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo')),
                ('tamaño', models.IntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('categoria', models.CharField(default='fisica_general', max_length=50, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('En revisión', 'En revisión')], default='Activo', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
