# Generated by Django 5.2.5 on 2025-08-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
    ]
