# Generated by Django 5.2.5 on 2025-08-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_add_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='firebase_uid',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='SinApellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=128),
        ),
    ]
