# Generated by Django 5.2.8 on 2025-11-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_componente_tema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temas',
            options={'ordering': ['curso', 'numero'], 'verbose_name': 'Temas', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AddField(
            model_name='documento',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios.temas', verbose_name='Temas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo_pdf',
            field=models.FileField(default=1, upload_to='pdfs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='temas',
            name='archivo',
            field=models.FileField(upload_to='tema/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
