# Generated by Django 5.2.7 on 2025-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='carpeta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
