# Generated by Django 5.2.6 on 2025-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Administrador', 'Administrador'), ('Profesor', 'Profesor'), ('Estudiante', 'Estudiante')], max_length=50, unique=True),
        ),
    ]
