# Generated by Django 5.2.6 on 2025-09-25 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_firebase_uid_remove_usuario_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_simulacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo_laboratorio', models.FileField(blank=True, upload_to='laboratorios/')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_usuarios', models.IntegerField()),
                ('usuarios_activos', models.IntegerField()),
                ('simulaciones_realizadas', models.IntegerField()),
                ('ingresos_periodo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuarios_activos_anterior', models.IntegerField(default=0)),
                ('simulaciones_realizadas_anterior', models.IntegerField(default=0)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingresos_anuales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteMembresias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_membresias', models.IntegerField()),
                ('membresias_mensuales', models.IntegerField()),
                ('membresias_semestrales', models.IntegerField()),
                ('membresias_anuales', models.IntegerField()),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteSimulaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulaciones_activas', models.IntegerField()),
                ('simulaciones_totales', models.IntegerField()),
                ('simulaciones_realizadas_mes', models.IntegerField(default=0)),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_usuarios', models.IntegerField()),
                ('usuarios_activos', models.IntegerField()),
                ('usuarios_inactivos', models.IntegerField()),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actividad', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones_completadas', to='usuarios.usuario')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_membresia', models.CharField(choices=[('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('expirado', 'Expirado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_membresia', models.CharField(choices=[('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(default='tarjeta', max_length=50)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.membresia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='usuarios.usuario')),
            ],
        ),
    ]
