# Generated by Django 5.2.8 on 2025-11-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_temas_options_documento_tema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionvisual',
            name='despliegue',
        ),
        migrations.RemoveField(
            model_name='configuracionvisual',
            name='estilo_menu',
        ),
        migrations.RemoveField(
            model_name='configuracionvisual',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='configuracionvisual',
            name='fuente',
        ),
        migrations.RemoveField(
            model_name='configuracionvisual',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='configuracionvisual',
            name='puede_probar',
        ),
    ]
