# Generated by Django 5.2.6 on 2025-10-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_rol_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='componente',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='profesor',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('suspendida', 'Suspendida')], default='activa', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=20),
        ),
    ]
