# Generated by Django 5.2.7 on 2025-10-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_laboratorio_carpeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='archivo',
        ),
    ]
