# Generated by Django 5.2.6 on 2025-10-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_administrador_estado_colegio_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='tipo',
        ),
        migrations.AddField(
            model_name='administrador',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='usuarios.colegio'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='usuarios.persona'),
        ),
    ]
