# Generated by Django 5.2.8 on 2025-11-22 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_configuracionvisual_despliegue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionvisual',
            name='colegio',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.colegio'),
            preserve_default=False,
        ),
    ]
