# Generated by Django 5.2.6 on 2025-10-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='archivo_laboratorio',
            field=models.FileField(blank=True, null=True, upload_to='laboratorios/'),
        ),
    ]
