# Generated by Django 5.2.6 on 2025-10-18 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_administrador_tipo_administrador_colegio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='usuarios.profesor'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='usuarios.usuario'),
        ),
    ]
