# Generated by Django 5.2.8 on 2025-11-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_configuracionvisual_colegio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionvisual',
            name='administrador',
        ),
    ]
