# Generated by Django 5.2.8 on 2025-11-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_configuracionvisual_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='carpeta',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
