# Generated by Django 5.2.6 on 2025-10-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_laboratorio_archivo_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
    ]
