# Generated by Django 5.2.7 on 2025-10-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_estudiante_profesor_estudiante_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario',
        ),
    ]
