# Generated by Django 5.2.6 on 2025-10-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_laboratorio_archivo'),
        ('usuarios', '0006_estudiante_profesor_estudiante_usuario'),
    ]

    operations = [
    ]
