# Generated by Django 5.2.7 on 2025-10-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_merge_20251018_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario',
        ),
    ]
