# Generated by Django 5.2.6 on 2025-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_documento_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('universitario', 'Universitario'), ('profesional', 'Profesional'), ('administrador', 'Administrador')], default='estudiante', max_length=20),
        ),
    ]
