# Generated by Django 5.2.7 on 2025-10-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_estudiante_profesor_remove_estudiante_usuario'),
    ]

    operations = [
    ]
