# Generated by Django 5.2.7 on 2025-10-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_merge_20251018_0932'),
        ('usuarios', '0009_add_carpeta_to_laboratorio'),
    ]

    operations = [
    ]
