# Generated by Django 5.2.6 on 2025-10-01 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del laboratorio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('archivo_entorno', models.FileField(blank=True, null=True, upload_to='entornos/', verbose_name='Archivo de entorno (zip / glb / otra)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del componente')),
                ('modelo_3d', models.FileField(blank=True, null=True, upload_to='modelos_3d/', verbose_name='Modelo 3D (.glb, .usdz, ...)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='componentes_imgs/', verbose_name='Imagen del componente')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('especificaciones', models.JSONField(blank=True, default=dict, verbose_name='Especificaciones técnicas (JSON)')),
                ('video_youtube', models.URLField(blank=True, verbose_name='Video YouTube (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='componentes.laboratory')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
    ]
