# Generated by Django 5.2.6 on 2025-10-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0001_initial'),
        ('usuarios', '0005_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='usuarios.laboratorio'),
        ),
        migrations.AlterField(
            model_name='component',
            name='especificaciones',
            field=models.TextField(blank=True, verbose_name='Especificaciones técnicas'),
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
    ]
